# Generated by Django 4.2.1 on 2023-06-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_alter_post_options_post_created_on_post_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
