# Generated by Django 4.2.1 on 2023-06-03 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0005_alter_post_options_remove_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_content', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('com_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postapp.user')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='postapp.user')),
                ('other_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_user', to='postapp.user')),
            ],
        ),
    ]
